CREATE TABLE PERSON(
                           person_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                           first_name VARCHAR2(200 CHAR ) NOT NULL,
                           last_name VARCHAR2(200 CHAR) NOT NULL,
                           PRIMARY KEY(person_id)
);
